MainlyCode\Reeleezee\ValueObject\ProductReferenceType:
    properties:
        code:
            expose: true
            access_type: public_method
            serialized_name: Code
            accessor:
                getter: getCode
                setter: setCode
            xml_attribute: true
            type: string
        internalRlzID:
            expose: true
            access_type: public_method
            serialized_name: InternalRlzID
            accessor:
                getter: getInternalRlzID
                setter: setInternalRlzID
            xml_attribute: true
            type: string
