MainlyCode\Reeleezee\ValueObject\ProductGroupReferenceType:
    properties:
        description:
            expose: true
            access_type: public_method
            serialized_name: Description
            accessor:
                getter: getDescription
                setter: setDescription
            xml_attribute: true
            type: string
